### PR TITLE
add failing test

### PR DESCRIPTION
**Pull request by ocefpaf**
See https://github.com/conda-forge/geopy-feedstock/pull/10#issuecomment-380893289

### CODE REVIEW

**Comment by ocefpaf** [comment]
Something else is amiss now @KostyaEsmukov.
I'm getting a

```python
ModuleNotFoundError: No module named 'geopy.distance.geodesic'; 'geopy.distance' is not a package
```

when `geographiclib` lib is present. I'll look closer at this later.

**Comment by KostyaEsmukov** [comment]
`geopy.distance` is a module, not a package. `geodesic` is a class defined in that module

**Comment by ocefpaf** [comment]
Yeah, conda import test is not that flexible. The latest commit should fix that test.

**Comment by KostyaEsmukov** [comment]
It works now. Thank you!

**Comment by ocefpaf** [comment]
Thanks for reporting and helping with the testing. (Fixing that was actually the easy part :smile:)

**Pull request merged**
